id: P8E25EC20
initial_creation_type: ocr
source_metadata:
  volumes:
    bda385ff92bc4b8aaca0fd401fb640ee:
      base_file: v015.txt
      image_group_id: I1PD95860
      title: དཔལ་གསང་བ་འདུས་པའི་རྒྱུད་ཀྱི་རྒྱུད་འགྲེལ།
      total_pages: 1453
      volume_number: 15
